# Generated by Django 5.2 on 2025-04-22 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='mobile_number',
            new_name='mobile',
        ),
    ]
