# Generated by Django 5.2 on 2025-05-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_rawtransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserJsonUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('json_file', models.JSONField()),
            ],
        ),
    ]
