# Generated by Django 5.2 on 2025-05-13 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_userjsonupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userjsonupload',
            old_name='dob',
            new_name='date_of_birth',
        ),
    ]
