# Generated by Django 5.2 on 2025-05-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_rename_dob_userjsonupload_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjsonupload',
            name='json_file',
            field=models.TextField(),
        ),
    ]
