# Generated by Django 5.2 on 2025-05-16 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_userjsonupload_json_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userjsonupload',
            old_name='json_file',
            new_name='json_data',
        ),
        migrations.RenameField(
            model_name='userjsonupload',
            old_name='mobile',
            new_name='mobile_number',
        ),
    ]
